//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kütüphane_Otomasyonu
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KutuphaneOtomasyonuEntities : DbContext
    {
        public KutuphaneOtomasyonuEntities()
            : base("name=KutuphaneOtomasyonuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Emanet> tbl_Emanet { get; set; }
        public virtual DbSet<tbl_Turler> tbl_Turler { get; set; }
        public virtual DbSet<tbl_Uyeler> tbl_Uyeler { get; set; }
        public virtual DbSet<tbl_Kitaplar> tbl_Kitaplar { get; set; }
        public virtual DbSet<tbl_Giris> tbl_Giris { get; set; }
    }
}
