//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kütüphane_Otomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Uyeler
    {
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string TC { get; set; }
        public string Tel { get; set; }
        public string Cinsiyet { get; set; }
        public short ID { get; set; }
    }
}
