//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kütüphane_Otomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Emanet
    {
        public short Sıra { get; set; }
        public string Üye_Adı { get; set; }
        public string Üye_Soyadı { get; set; }
        public string Üye_TC { get; set; }
        public string Üye_Tel { get; set; }
        public int Kitap_İd { get; set; }
        public string Kitap_Adı { get; set; }
        public string Yazar_Adı { get; set; }
        public string Yayınevi { get; set; }
        public string Verilme_Tarihi { get; set; }
        public string İade_Tarihi { get; set; }
        public string Teslim_Tarihi { get; set; }
        public string Durum { get; set; }
        public string Ceza { get; set; }
    }
}
